/*
 * Waiting List Api
 *
 * Hospital Employee List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: kapusta.jergus@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package xkapustaj_wl

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type HospitalsAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // CreateHospital - Saves new hospital definition
   CreateHospital(ctx *gin.Context)

    // DeleteHospital - Deletes specific hospital
   DeleteHospital(ctx *gin.Context)

 }

// partial implementation of HospitalsAPI - all functions must be implemented in add on files
type implHospitalsAPI struct {

}

func newHospitalsAPI() HospitalsAPI {
  return &implHospitalsAPI{}
}

func (this *implHospitalsAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodPost, "/hospital", this.CreateHospital)
  routerGroup.Handle( http.MethodDelete, "/hospital/:ambulanceId", this.DeleteHospital)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateHospital - Saves new hospital definition
// func (this *implHospitalsAPI) CreateHospital(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // DeleteHospital - Deletes specific hospital
// func (this *implHospitalsAPI) DeleteHospital(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

