/*
 * Waiting List Api
 *
 * Hospital Employee List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: kapusta.jergus@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package xkapustaj_wl

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type JkaEmployeeAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // GetEmployee - Provides the employee
   GetEmployee(ctx *gin.Context)

 }

// partial implementation of JkaEmployeeAPI - all functions must be implemented in add on files
type implJkaEmployeeAPI struct {

}

func newJkaEmployeeAPI() JkaEmployeeAPI {
  return &implJkaEmployeeAPI{}
}

func (this *implJkaEmployeeAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodGet, "/employee-list/:ambulanceId/entries/:employeeId", this.GetEmployee)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // GetEmployee - Provides the employee
// func (this *implJkaEmployeeAPI) GetEmployee(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

