/*
 * Waiting List Api
 *
 * Hospital Employee List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: kapusta.jergus@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package xkapustaj_wl

import (
	"time"
)

// Timesheet - Describes the schedule of hospital employee
type Timesheet struct {

	// Unique identifier of the timesheet
	Id string `json:"id"`

	// Unique identifier of the employee
	EmployeeId string `json:"employeeId"`

	// number of hours worked that day
	Hours int32 `json:"hours"`

	// description of the shift
	Description string `json:"description"`

	// day of the shift
	Date time.Time `json:"date"`
}
