/*
 * Waiting List Api
 *
 * Hospital Employee List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: kapusta.jergus@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package xkapustaj_wl

type EmployeeListEntry struct {

	// Unique id of the entry in this waiting list
	Id string `json:"id"`

	// Name of patient in waiting list
	Name string `json:"name"`

	// Unique identifier of the patient known to Web-In-Cloud system
	PatientId string `json:"patientId"`

	// Name of the job position
	JobTitle string `json:"jobTitle"`
}
