/*
 * Waiting List Api
 *
 * Hospital Employee List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: kapusta.jergus@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package xkapustaj_wl

import (
    "github.com/gin-gonic/gin"
)

func AddRoutes(engine *gin.Engine) {
  group := engine.Group("/api")
  
  {
    api := newJkaEmployeeAPI()
    api.addRoutes(group)
  }
  
  {
    api := newJkaEmployeeListAPI()
    api.addRoutes(group)
  }
  
  {
    api := newJkaTimesheetAPI()
    api.addRoutes(group)
  }
  
  {
    api := newJkaTimesheetsAPI()
    api.addRoutes(group)
  }
  
}